server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/egs?allowPublicKeyRetrieval=true&useSSL=false
    username: egs
    password: egs
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

